####### UltraJoinSettings Config File #######


##### First Join 

### Welcome Form

# If you set this to 'true' new Players will get an UI with Basic Server informations.

WelcomeUI: true

# Here you can edit the Form.
# use '§' for Colors
# to add an empty row use '\n'

# Title of the Welcome Form:

Welcome-Title: "§bWelcome!"

# Content of the Welcome Form:

Welcome-Content: "§aWelcome on this Server!\n\§fYou got free Items for a got beginning on this Server!\n§ePlease read the Rules.\n\n§cHave Fun!"

# Button of the Welcome Form:

Welcome-Button: "Great!"


##### Other Settings

### Title

# Set this to false to disable this feature.

Join-Title: "§aWelcome!"
